on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
      - develop

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: lint_and_build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: Deploy Production
        uses: borales/actions-yarn@v3.0.0
        with:
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          cmd: deploy
  deploy_develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    needs: lint_and_build
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: Deploy Develop
        uses: borales/actions-yarn@v3.0.0
        with:
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          cmd: deploy:beta
